{"@t":"2022-02-11T07:39:15.8327330Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.17.2.","TimingId":"366cbf4","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:15.8646683Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Flight2Orbit","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\","MachineName":"AAR00118","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:15.9954175Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:15.9974119Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:17.1096997Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"f970e85","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:17.2853953Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":174,"TimingId":"f970e85","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:17.9570953Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:18.1836260Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:18.3143628Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:18.3942083Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":2581,"TimingId":"366cbf4","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"709b7b5f-408e-4d8f-97b8-94ea0225b6d8"}
{"@t":"2022-02-11T07:39:18.9341639Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:18.9351625Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"a436a05a-084e-47c2-a545-ad55b691d6a6"}
{"@t":"2022-02-11T07:39:18.9371610Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"a436a05a-084e-47c2-a545-ad55b691d6a6"}
{"@t":"2022-02-11T07:39:18.9371610Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:19.7525812Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:19.7525812Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:19.7555750Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.2576616Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"a41ce13","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.3175453Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":60,"TimingId":"a41ce13","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.3355100Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"e41eb3d","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.3424988Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":6,"TimingId":"e41eb3d","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.7107857Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"InternalIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.7127841Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"MembersIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.7138006Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"ExternalIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:21.7158101Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"e183fd30-0bcd-4d94-a347-94a995f8b255"}
{"@t":"2022-02-11T07:39:39.7809904Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"57ad3a53-9a65-4ce5-95bf-a5c53c0d1857"}
{"@t":"2022-02-11T07:39:39.7819639Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"57ad3a53-9a65-4ce5-95bf-a5c53c0d1857"}
{"@t":"2022-02-11T07:40:45.5008174Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"07855283-e04e-4dea-a0db-32b419a1e992"}
{"@t":"2022-02-11T07:40:45.5946377Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"07855283-e04e-4dea-a0db-32b419a1e992"}
{"@t":"2022-02-11T07:43:26.0463857Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The network connection was aborted by the local system.) ---> System.ComponentModel.Win32Exception (0x80004005): The network connection was aborted by the local system\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)\r\n   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)\r\n   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)\r\n   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)\r\n   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)\r\n   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)\r\n   at StackExchange.Profiling.Data.ProfiledDbConnection.BeginDbTransaction(IsolationLevel isolationLevel) in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbConnection.cs:line 138\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:8fca6b20-ffd5-4301-9adc-8053a9ee6d40\r\nError Number:1236,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T07:45:57.8546344Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"00bd20a9-38a7-4fd5-85d6-c23a161c8518"}
{"@t":"2022-02-11T07:45:57.9096342Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"00bd20a9-38a7-4fd5-85d6-c23a161c8518"}
{"@t":"2022-02-11T07:47:09.2698749Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"2cb0d2fe-b269-4fea-8ee5-5d9b0982ebec"}
{"@t":"2022-02-11T07:47:09.3158762Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"2cb0d2fe-b269-4fea-8ee5-5d9b0982ebec"}
{"@t":"2022-02-11T07:50:39.2637133Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":8,"HttpRequestId":"5135dbd5-2971-4761-9eee-f7da7222b04a"}
{"@t":"2022-02-11T07:50:39.3437116Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":83,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":8,"HttpRequestId":"5135dbd5-2971-4761-9eee-f7da7222b04a"}
{"@t":"2022-02-11T08:19:07.6137226Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":229,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":9,"HttpRequestId":"c4023a84-ce95-46e4-87ca-42c9f11fa59b"}
{"@t":"2022-02-11T08:19:07.6137226Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":229,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":9,"HttpRequestId":"c4023a84-ce95-46e4-87ca-42c9f11fa59b"}
{"@t":"2022-02-11T08:38:03.8018291Z","@mt":"Exception","@l":"Error","@x":"ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 609 : No image exists at D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\media\\f1xdeimc\\rock-2.png","SourceContext":"ImageProcessor.Web.HttpModules.ImageProcessingModule","ProcessId":10620,"ProcessName":"iisexpress","ThreadId":122,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR","HttpRequestNumber":10,"HttpRequestId":"30c03d9c-c783-4d5c-bd9d-57b596d6c496"}
{"@t":"2022-02-11T12:40:31.1911221Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.17.2.","TimingId":"1c7a146","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:31.2279206Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Flight2Orbit","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\","MachineName":"AAR00118","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:31.3869208Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:31.3899191Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:32.6255212Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"bad1d97","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:32.7885232Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":162,"TimingId":"bad1d97","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:33.5116345Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:33.7356703Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:33.8556695Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:33.9446341Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":2770,"TimingId":"1c7a146","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"94e12ba8-9867-4cd9-b7ca-16983ea50fe5"}
{"@t":"2022-02-11T12:40:34.5426410Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:34.5426410Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":5,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"56b9cb76-1699-4d24-8814-b893f31ea645"}
{"@t":"2022-02-11T12:40:34.5426410Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"c45d64cb-170e-45c7-9a33-c6cd8b5cb0f6"}
{"@t":"2022-02-11T12:40:34.5616344Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:34.5616344Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"c45d64cb-170e-45c7-9a33-c6cd8b5cb0f6"}
{"@t":"2022-02-11T12:40:34.5706409Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":5,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"56b9cb76-1699-4d24-8814-b893f31ea645"}
{"@t":"2022-02-11T12:40:35.5266356Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:35.5276372Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:35.5356349Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.0716493Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"befdec5","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.1496329Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":77,"TimingId":"befdec5","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.1706371Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"2c7c6ab","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.1726347Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":1,"TimingId":"2c7c6ab","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.6156344Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"InternalIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.6166334Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"MembersIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.6166334Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"ExternalIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:38.6196345Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"f4fae263-2187-44db-9eee-7dcc7a01dae2"}
{"@t":"2022-02-11T12:40:50.1387388Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"72953644-1a8c-4c03-82ef-6f09c97920ee"}
{"@t":"2022-02-11T12:40:50.1387388Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"72953644-1a8c-4c03-82ef-6f09c97920ee"}
{"@t":"2022-02-11T12:54:23.3637627Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The network connection was aborted by the local system.) ---> System.ComponentModel.Win32Exception (0x80004005): The network connection was aborted by the local system\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)\r\n   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)\r\n   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)\r\n   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)\r\n   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)\r\n   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)\r\n   at StackExchange.Profiling.Data.ProfiledDbConnection.BeginDbTransaction(IsolationLevel isolationLevel) in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbConnection.cs:line 138\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:05068156-8e16-43ac-b1c0-75007237734c\r\nError Number:1236,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":195,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T12:54:43.5519424Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":197,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T12:55:03.2919287Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":163,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T12:55:03.2929301Z","@mt":"Failed to update server record in database.","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Persistence.Repositories.Implement.ServerRegistrationRepository.PerformGetAll(Int32[] ids) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Repositories\\Implement\\ServerRegistrationRepository.cs:line 59\r\n   at Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll) in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\NoCacheRepositoryCachePolicy.cs:line 47\r\n   at Umbraco.Core.Services.Implement.ServerRegistrationService.TouchServer(String serverAddress, String serverIdentity, TimeSpan staleTimeout) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ServerRegistrationService.cs:line 54\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.TouchServerTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 206\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":140,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T12:55:23.0883173Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":175,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T12:55:43.1160929Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":184,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:03:49.5236025Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":133,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:06:05.2283548Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":82,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:06:50.5979021Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:06:50.6778458Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (205 <= 205 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:07:15.8090959Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (205 <= 205 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:07:15.8090959Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:07:31.0579274Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":30,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:07:31.0579274Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:08:11.4958586Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":243,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:08:11.4958586Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":241,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:09:52.2446935Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":263,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:09:52.2446935Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":262,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:11:05.6823695Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":273,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:11:07.7491171Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":263,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:11:36.4341273Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":260,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:11:38.4545522Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":248,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:18:54.4738250Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":159,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:18:56.5457229Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":163,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:19:29.7799171Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":165,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:19:31.8045215Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":169,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:19:32.1027539Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":170,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:20:25.2340247Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":181,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:20:27.2768164Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":183,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:20:42.5114335Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":188,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:20:42.5274151Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":189,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:20:57.7105433Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":200,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:20:57.7105433Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":205,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:21:02.9549288Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":210,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:21:02.9549288Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":209,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:21:08.0873058Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":216,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:21:08.1031588Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":212,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:21:13.2634979Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (204 <= 204 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":217,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:21:13.2634979Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":218,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:22:54.0227898Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (203 <= 203 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":144,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:22:54.0227898Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":140,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:22:54.3209489Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (203 <= 203 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:23:19.2116237Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (203 <= 203 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":21,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:23:19.2116237Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:24:14.5993312Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":280,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:24:14.6161551Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (203 <= 203 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":281,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:24:14.8965032Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":283,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:26:46.4196247Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":238,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:26:46.4196247Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (203 <= 203 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":311,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:27:51.9144527Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (203 <= 203 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":286,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:27:51.9144527Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":283,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:29:17.5241759Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":225,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:29:17.5402137Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (202 <= 202 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":227,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:29:42.7307299Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":219,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:29:42.7466324Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (201 <= 201 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":230,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:31:54.4305596Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":164,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:31:54.4456895Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (201 <= 201 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":162,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:34:05.5363933Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":119,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:34:05.5363933Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (201 <= 201 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":117,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:36:56.7153703Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (201 <= 201 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":59,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:36:56.8234925Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":58,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:36:57.0263555Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (201 <= 201 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:39:37.9123936Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":272,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"e91edbb7-c369-4abc-99d6-0713d2b92f07"}
{"@t":"2022-02-11T13:39:37.9123936Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":272,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"e91edbb7-c369-4abc-99d6-0713d2b92f07"}
{"@t":"2022-02-11T13:46:15.7501785Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (200 <= 200 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":334,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:46:15.7653065Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":331,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:57:10.9091666Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (199 <= 199 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":232,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:57:11.0489739Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":23,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:57:11.3624934Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":242,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:58:01.1948063Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:58:01.1948063Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (199 <= 199 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":139,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T13:59:08.8960711Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: oliver.gjesing@akqa.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":245,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"6f287bea-dffe-4971-b71f-bc55c84d18f8"}
{"@t":"2022-02-11T14:03:18.5828319Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":42,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T14:03:18.5986875Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (199 <= 199 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":46,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T14:03:38.6969295Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":50,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T14:03:38.7119271Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (199 <= 199 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T14:04:03.9281996Z","@mt":"Concurrent merge failed for index: InternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _bl: fieldsReader shows 1 but segmentInfo shows 3\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":73,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-11T14:04:03.9281996Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: docs out of order (198 <= 198 )\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":27688,"ProcessName":"iisexpress","ThreadId":58,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
